# Generated by Django 4.2.7 on 2023-12-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0006_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='video',
            field=models.FileField(blank=True, upload_to='meep_videos/'),
        ),
    ]
