# Generated by Django 4.2.7 on 2023-12-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0010_remove_meep_video_alter_profile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='meep_videos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='homepage_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
